import "pkg:/components/CustomComponents/BaseFocusManager/BaseFocusManager.bs"

sub init()
    m.navigationController = m.global.navigationController
    m.focusManager = new BaseFocusManager(m.top)
end sub

REM : **** Default Implementations ****
sub onSetInitialFocus()
end sub

sub didGainFocus()
    ' ?"!---- baseGroup + didGainFocus"
    if m.focusManager <> invalid
        m.focusManager.didGainFocus()
    end if
end sub