namespace MainSceneEventHandler
    sub new()
    end sub

    function handleEvent(key as RemoteButtons, press as boolean) as boolean
        if press
            if key = RemoteButtons.OK
                m._handleOkPress()
                result = true
            end if
        end if
        return true
    end function

    sub _handleOkPress()
        gotoPlayerScreen()
    end sub
end namespace