class MainSceneEventHandler
    viewModel as object

    sub new(viewModel as object)
        m.viewModel = viewModel
    end sub

    function handleEvent(key as RemoteButtons, press as boolean) as boolean
        if press
            if key = RemoteButtons.OK
                m._handleOkPress()
                result = true
            end if
        end if
        return true
    end function

    sub _handleOkPress()
        gotoPlayerScreen()
    end sub
end class